name: Maintain Podcast Feed
description: Automatically maintain an RSS feed for an audio-only version of a YouTube podcast.

inputs:
  show:
    description: "The name of the show."
    required: true
    type: string
  num_eps:
    description: "The number of recent episodes to check."
    default: 1
  yt_url:
    description: "The URL for the YouTube podcast."

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Install ffmpeg
      uses: FedericoCarboni/setup-ffmpeg@v3

    - name: Instal deps
      shell: bash
      run: pip install -r requirements.txt

    - name: Create cookies file
      shell: bash
      run: echo "${{ secrets.YOUTUBE_COOKIES }}" > cookies.txt

    - name: Get all videos from channel
      shell: bash
      run: |
        yt-dlp --flat-playlist -J ${{ inputs.yt_url }} --extractor-args youtubetab:approximate_date | jq -r '[.entries[] | {title, url, timestamp, description, thumbnail: .thumbnails[0].url}]' > videos.json

    - name: Upload list for debugging
      uses: actions/upload-artifact@v4
      with:
        name: videos.json
        path: videos.json

    - name: Download missing episodes and add to RSS feed
      shell: bash
      run: ./get_eps.sh videos.json ${{ inputs.num_eps }} ${{ inputs.show }}

    - name: Upload feed for debugging
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.show }}.rss
        path: ${{ inputs.show }}/feed.rss

    - name: Remove cookies file
      shell: bash
      run: rm cookies.txt
      
    - name: Check-in updates
      uses: stefanzweifel/git-auto-commit-action@v6